development:
      host: localhost
      adapter: mysql2
      database: clinical_ms
      port: 3306
      encoding: utf8
      reconnect: false
      pool: 5
      username: root
      password: 
      
test:
      host: localhost
      adapter: mysql2
      database: clinical_ms_test
      port: 3306
      encoding: utf8
      reconnect: false
      pool: 5
      username: root
      password: 
